# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78186a9d3768c24ca25b2429fc3bb9e8802cb7bcd22330e6bef6f09f81847a3e17bc3b0dc36ef6e09614426ffaeb8c720e5115e085a6a69ae1d5fc9af017933b

test:
  secret_key_base: 3472098be8e5f705258fd69294eaed0fb347164c9a8bfa8e6921642cc7b313fde0b8e04c1d30c45155c3e3e7ac4e956fc07659293574d915755e93350f7a270e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
